### PR TITLE
Update Gemfile

### PR DESCRIPTION
**Pull request by pratikganvir**
Unspecified savon version causing weird issues. Having issues with savon 2.\* , best works with 1.0.0.

### CODE REVIEW

**Comment by kennym** [comment]
What kind of issues do you encounter?

**Comment by arikrak** [comment]
I tried using the gem a while ago, but I ran into the following issue:  

```
i = Ideone.new('NAME', 'PASS')
ArgumentError: wrong number of arguments (0 for 1)
from .../gems/ruby-1.9.3-p392/gems/savon-2.3.0/lib/savon/options.rb:72:in `wsdl'
```

I guess I'll try it again with an earlier version of Savon.

**Comment by arikrak** [comment]
OK, I was able to initialize the Ideone object now that I switched to Savon 1.1.0. 
(If only I knew that previously... )

**Comment by kennym** [comment]
I can reproduce that issue... I am updating to Savon 2

**Comment by kennym** [comment]
Finally had time to fix this. I have released v 2.0.0 with support for Savon 2

**Pull request closed without merging**
